---
- name: Update and upgrade Ubuntu server
  hosts: all
  become: yes
  tasks:
    - name: Update the apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Reboot the server if needed
      ansible.builtin.reboot:
        reboot_timeout: 600
