name: Run Azure Login with OIDC

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private action repository
        uses: actions/checkout@v2
        with:
          repository: Test-OIDC-connection
          ref: environment
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Ensure this secret exists

      - name: Azure login
        uses: ./Test-OIDC-connection/.github/workflows/workflow.yml # Use local path if the action is in the same repo
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        run: |
          az account show
